<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Introduction to JustifyAlpha • JustifyAlpha</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Introduction to JustifyAlpha">
<meta property="og:description" content="JustifyAlpha">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">JustifyAlpha</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.1</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/intro_to_justifieR.html">Introduction to JustifyAlpha</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="intro_to_justifieR_files/header-attrs-2.8/header-attrs.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Introduction to JustifyAlpha</h1>
                        <h4 class="author">Daniel Lakens &amp; Maximilian Maier</h4>
            
            <h4 class="date">2021-06-08</h4>
      
      
      <div class="hidden name"><code>intro_to_justifieR.Rmd</code></div>

    </div>

    
    
<div id="vignette-accompanying-justify-your-alpha-a-primer-on-two-practical-approaches" class="section level1">
<h1 class="hasAnchor">
<a href="#vignette-accompanying-justify-your-alpha-a-primer-on-two-practical-approaches" class="anchor"></a>Vignette Accompanying “Justify Your Alpha: A Primer on Two Practical Approaches”</h1>
<p>The goal of JustifyAlpha is to provide ways for researchers to justify their alpha level when designing studies. Two approaches are currently implemented. The first function <em>optimal_alpha</em> allows users to computed balanced or minimized Type 1 and Type 2 error rates. The second approach uses the function <em>ttestEvidence</em> or <em>ftestEvidence</em> to lower the alpha level as a function of the sample size to prevent Lindley’s paradox.</p>
<div id="installation" class="section level2">
<h2 class="hasAnchor">
<a href="#installation" class="anchor"></a>Installation</h2>
<p>You can install the released version of JustifyAlpha from <a href="https://github.com/Lakens/JustifyAlpha">GitHub</a> with:</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">devtools</span><span class="fu">::</span><span class="fu"><a href="https://devtools.r-lib.org//reference/remote-reexports.html">install_github</a></span><span class="op">(</span><span class="st">"Lakens/JustifyAlpha"</span><span class="op">)</span></code></pre></div>
</div>
</div>
<div id="minimizing-error-rates" class="section level1">
<h1 class="hasAnchor">
<a href="#minimizing-error-rates" class="anchor"></a>Minimizing Error Rates</h1>
<p>Assume we plan to perform an indepedent <em>t</em>-test, where our smallest effect size of interest is d = 0.5, and we are planning to collect 64 participants in each condition. We would normally calculate power as follows:</p>
<p><code>pwr.t.test(d = 0.5, n = 64, sig.level = 0.05, type = 'two.sample', alternative = 'two.sided')$power</code></p>
<p>This analysis tells us that we have 80% power with a 5% alpha level for our smallest effect size of interest, d = 0.5, when we collect 64 participants in each condition.</p>
<p>If we design 2000 studies like this, the number of Type 1 and Type 2 errors we make depend on how often the null hypothesis is true, and how often the alternative hypothesis is true. Let’s assume both are equally likely. This means that in 0.5 × 2000 = 1000 studies the null hypothesis is true, and we will make 0.05 × 1000 = 50 Type 1 errors, so in 50 studies we will find a significant result, even though there is no true effect. In 0.5 × 2000 = 1000 studies the alternative hypothesis is true, and with 80% power we will make 0.2 × 1000 = 200 Type 2 errors, so in 200 studies we will not observe a significant result even if there is a true effect. Combining Type 1 and Type 2 errors, in the long run, we should expect 50 + 200 = 250 of our 2000 studies to yield an error. The combined error rate is therefore 250/2000 = 0.125.</p>
<p>The goal in Neyman-Pearson hypothesis testing is to control the number of errors we make, as we perform hypothesis tests. Researchers often rely on convention when setting error rates, and there is no special reason to set the Type 1 error rate at 5% and the Type 2 error rate at 20%. Indeed, there might be better choices when designing studies. For example, when collecting 64 participants per condition, we can set the Type 1 and Type 2 error rates in a way that reduced the number of errors we make, such that from the 2000 studies less than 250 studies yield misleading conclusions.</p>
<p>We can use the <em>optimal_alpha</em> function to compute the minimized error rates. The optimal_alpha function takes as input a power function, the relative cost of Type 1 and Type 2 errors (the default is 1, meaning both errors are equally costly), The prior odds of H1 versus H0 (the default is 1, meaning H1 and H0 are believed to be equally likely). We can convert odds to probabilities by calculating <span class="math inline">\(odds/(1+odds)\)</span>. For example, if the prior odds are 1, the prior probability is 1/(1+1) = 0.5. If the prior odds of H1 compared to H0 are 2, the prior probability of H1 is 2/(2+1) = 0.66. Analogous, we can convert from probability to odds by dividing the probability by 1 minus the probability. For example, if the prior probability of H1 is 0.66. The prior odds of H1 compared to H0 are 0.66/(1-0.66) = 2. Apart from the prior odds, we also need to specify whether to compute the minimized combined error rate (“minimize”) or balanced error rates (“balanced”), and whether to provide output for each iteration of the optimization function or not, and a plot or not. An example of the us of the function is provided below:</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res1</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/optimal_alpha.html">optimal_alpha</a></span><span class="op">(</span>power_function <span class="op">=</span> <span class="st">"pwr.t.test(d=0.5, n=64, sig.level = x, type='two.sample', alternative='two.sided')$power"</span>,
              error <span class="op">=</span> <span class="st">"minimize"</span>,
              costT1T2 <span class="op">=</span> <span class="fl">1</span>,
              priorH1H0 <span class="op">=</span> <span class="fl">1</span>,
              verbose <span class="op">=</span> <span class="cn">FALSE</span>, 
              printplot <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<p><img src="intro_to_justifieR_files/figure-html/minimize-1.png" width="576"></p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res1</span><span class="op">$</span><span class="va">alpha</span></code></pre></div>
<pre><code>## [1] 0.09978841</code></pre>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res1</span><span class="op">$</span><span class="va">beta</span></code></pre></div>
<pre><code>## [1] 0.1215426</code></pre>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res1</span><span class="op">$</span><span class="va">errorrate</span></code></pre></div>
<pre><code>## [1] 0.1106655</code></pre>
<p>The output indicates that given the specific settings (e.g., weighing Type 1 and Type 2 errors equally, expecting H1 and H0 to be equally likely to be true) the combined error rate is minimized when (rounding to 3 decimal places) the alpha level is set to 0.10 (indicated by res$alpha), and the Type 2 error rate is set to 0.122 (indicated by res$beta). The expected error rate is then 0.111. In other words, if a researcher is interested in effects of d = 0.5, and plans to collect 64 participants in each condition, setting the Type 1 error rate to 10% will increase the power to 87.8%. If we would perform 2000 studies designed with these error rates, we would observe 0.5 (the prior probability that H0 is true) × 0.100 (the alpha level) × 2000 = 100 Type 1 errors, and 0.5 (the prior probability that H1 is true) × 0.122 (the Type 2 error rate) × 2000 = 122 Type 2 errors, for a total of 222 errors instead of 250. The combined error rate is therefore 222/2000 = 0.111. Indeed ,this is the value provided as the <code>errorrate</code>. In other words, by choosing a more optimal alpha level, we can design lines of research more efficiently, because we are less likely to make errors in our statistical inferences. This did increase the probability of making a Type 1 error (because we increased the alpha level), but this is compensated by reducing the probability of a Type 2 error even more.</p>
<p>The figure below recreates Figure 2 in Mudge et al, 2012.</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">resplot1</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/optimal_alpha.html">optimal_alpha</a></span><span class="op">(</span>power_function <span class="op">=</span> <span class="st">"pwr::pwr.t.test(d = 1, n = 3, sig.level = x, type = 'two.sample', alternative = 'two.sided')$power"</span>, error <span class="op">=</span> <span class="st">"minimize"</span>, costT1T2 <span class="op">=</span> <span class="fl">1</span>, printplot <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>
<span class="va">resplot2</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/optimal_alpha.html">optimal_alpha</a></span><span class="op">(</span>power_function <span class="op">=</span> <span class="st">"pwr::pwr.t.test(d = 1, n = 10, sig.level = x, type = 'two.sample', alternative = 'two.sided')$power"</span>, error <span class="op">=</span> <span class="st">"minimize"</span>, costT1T2 <span class="op">=</span> <span class="fl">1</span>, printplot <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>
<span class="va">resplot3</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/optimal_alpha.html">optimal_alpha</a></span><span class="op">(</span>power_function <span class="op">=</span> <span class="st">"pwr::pwr.t.test(d = 1, n = 30, sig.level = x, type = 'two.sample', alternative = 'two.sided')$power"</span>, error <span class="op">=</span> <span class="st">"minimize"</span>, costT1T2 <span class="op">=</span> <span class="fl">1</span>, printplot <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>

<span class="va">plot_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span><span class="va">resplot1</span><span class="op">$</span><span class="va">plot_data</span>, <span class="va">resplot2</span><span class="op">$</span><span class="va">plot_data</span>, <span class="va">resplot3</span><span class="op">$</span><span class="va">plot_data</span><span class="op">)</span>
<span class="va">plot_data</span><span class="op">$</span><span class="va">n</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">10</span>, <span class="fl">30</span><span class="op">)</span>, each <span class="op">=</span> <span class="fl">9999</span><span class="op">)</span><span class="op">)</span>

<span class="va">w_c_alpha_plot</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span>data<span class="op">=</span><span class="va">plot_data</span>, <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">alpha_list</span>, y<span class="op">=</span><span class="va">w_c_list</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_line</span><span class="op">(</span>size <span class="op">=</span> <span class="fl">1.3</span>, <span class="fu">aes</span><span class="op">(</span>linetype <span class="op">=</span> <span class="va">n</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_point</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">resplot1</span><span class="op">$</span><span class="va">alpha</span>, y <span class="op">=</span> <span class="op">(</span><span class="fl">1</span> <span class="op">*</span> <span class="va">resplot1</span><span class="op">$</span><span class="va">alpha</span> <span class="op">+</span> <span class="fl">1</span> <span class="op">*</span> <span class="op">(</span><span class="va">resplot1</span><span class="op">$</span><span class="va">beta</span><span class="op">)</span><span class="op">)</span> <span class="op">/</span> <span class="op">(</span><span class="fl">1</span> <span class="op">+</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span>, color<span class="op">=</span><span class="st">"red"</span>, size <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_point</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">resplot2</span><span class="op">$</span><span class="va">alpha</span>, y <span class="op">=</span> <span class="op">(</span><span class="fl">1</span> <span class="op">*</span> <span class="va">resplot2</span><span class="op">$</span><span class="va">alpha</span> <span class="op">+</span> <span class="fl">1</span> <span class="op">*</span> <span class="op">(</span><span class="va">resplot2</span><span class="op">$</span><span class="va">beta</span><span class="op">)</span><span class="op">)</span> <span class="op">/</span> <span class="op">(</span><span class="fl">1</span> <span class="op">+</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span>, color<span class="op">=</span><span class="st">"red"</span>, size <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_point</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">resplot3</span><span class="op">$</span><span class="va">alpha</span>, y <span class="op">=</span> <span class="op">(</span><span class="fl">1</span> <span class="op">*</span> <span class="va">resplot3</span><span class="op">$</span><span class="va">alpha</span> <span class="op">+</span> <span class="fl">1</span> <span class="op">*</span> <span class="op">(</span><span class="va">resplot3</span><span class="op">$</span><span class="va">beta</span><span class="op">)</span><span class="op">)</span> <span class="op">/</span> <span class="op">(</span><span class="fl">1</span> <span class="op">+</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span>, color<span class="op">=</span><span class="st">"red"</span>, size <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">theme_minimal</span><span class="op">(</span>base_size <span class="op">=</span> <span class="fl">16</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">scale_x_continuous</span><span class="op">(</span><span class="st">"alpha"</span>, <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">1</span>,<span class="fl">0.1</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">scale_y_continuous</span><span class="op">(</span><span class="st">"weighted combined error rate"</span>, <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">1</span>,<span class="fl">0.1</span><span class="op">)</span>, limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span>
<span class="va">w_c_alpha_plot</span></code></pre></div>
<p><img src="intro_to_justifieR_files/figure-html/mudgeplot-1.png" width="576"></p>
<div id="balancing-error-rates" class="section level2">
<h2 class="hasAnchor">
<a href="#balancing-error-rates" class="anchor"></a>Balancing Error Rates</h2>
<p>You can choose to minimize the combined error rates, but you can also decide that it makes most sense to balance the error rates. For example, you might think a Type 1 error is just as problematic as a Type 2 error, and therefore, you want to design a study that has balanced error rates for a smallest effect size of interest (e.g., a 5% Type 1 error rate and a 95% Type 2 error rate). The <code>optimal_alpha</code> function can compute the alpha level that would lead to a balanced Type 2 error rate.</p>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res2</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/optimal_alpha.html">optimal_alpha</a></span><span class="op">(</span>power_function <span class="op">=</span> <span class="st">"pwr.t.test(d=0.5, n=64, sig.level = x, type='two.sample', alternative='two.sided')$power"</span>,
              error <span class="op">=</span> <span class="st">"balance"</span>,
              costT1T2 <span class="op">=</span> <span class="fl">1</span>,
              priorH1H0 <span class="op">=</span> <span class="fl">1</span>,
              verbose <span class="op">=</span> <span class="cn">FALSE</span>, 
              printplot <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<p><img src="intro_to_justifieR_files/figure-html/balance-1.png" width="576"></p>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res2</span><span class="op">$</span><span class="va">alpha</span></code></pre></div>
<pre><code>## [1] 0.1111217</code></pre>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res2</span><span class="op">$</span><span class="va">beta</span></code></pre></div>
<pre><code>## [1] 0.1110457</code></pre>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res2</span><span class="op">$</span><span class="va">errorrate</span></code></pre></div>
<pre><code>## [1] 0.1110837</code></pre>
<p>This balances the Type 1 and Type 2 error rates (with a maximum difference between the two of 0.0001). The alpha level is 11.11%, and the power is 88.9% (or the Type 2 error rate is 11.1%). Choosing to balance error rates is only slightly less efficient than minimizing the combined error rate in this example, with a combined error rate when balancing Type 1 and 2 errors of 22.22% compared to a minimized error rate of 22.13%.</p>
</div>
</div>
<div id="relative-costs-of-type-1-and-type-2-errors" class="section level1">
<h1 class="hasAnchor">
<a href="#relative-costs-of-type-1-and-type-2-errors" class="anchor"></a>Relative costs of Type 1 and Type 2 errors</h1>
<p>So far we have assumed a Type 1 error and Type 2 error are equally costly. This means that we consider the consequences of a false positive just as bad as the consequences of a false negative. This is not the default in psychology, where researchers typically treat Type 1 errors as 4 times as bad as Type 2 errors. This is based on Cohen (1988), who proposed to aim for 80% power, because we use an alpha of 5%. The <code>optimal_alpha</code> function users to set the relative cost of Type 1 and Type 2 errors, <code>costT1T2</code>. By default this parameter is set to 1, meaning both types of errors are weighed equally. Changing the value to 4 means that Type 1 errors are weighed 4 times as much as Type 2 errors, or 4:1. This will change the weight of Type 1 errors compared to Type 2 errors, and thus also the alpha level at which combined costs of Type 1 and Type 2 errors are minimized.</p>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res3</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/optimal_alpha.html">optimal_alpha</a></span><span class="op">(</span>power_function <span class="op">=</span> <span class="st">"pwr.t.test(d=0.5, n=64, sig.level = x, type='two.sample', alternative='two.sided')$power"</span>,
              error <span class="op">=</span> <span class="st">"minimize"</span>,
              costT1T2 <span class="op">=</span> <span class="fl">4</span>,
              priorH1H0 <span class="op">=</span> <span class="fl">1</span>,
              verbose <span class="op">=</span> <span class="cn">FALSE</span>, 
              printplot <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<p><img src="intro_to_justifieR_files/figure-html/cost%20minimize-1.png" width="576"></p>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res3</span><span class="op">$</span><span class="va">alpha</span></code></pre></div>
<pre><code>## [1] 0.03268853</code></pre>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res3</span><span class="op">$</span><span class="va">beta</span></code></pre></div>
<pre><code>## [1] 0.2524248</code></pre>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res3</span><span class="op">$</span><span class="va">errorrate</span></code></pre></div>
<pre><code>## [1] 0.07663579</code></pre>
<p>Now, the alpha level that minimizes the combined Type 1 and Type 2 error rates is 3.27%. With 64 participants in each condition of an independent <em>t</em>-test the Type 2 error is 25.24%, and the expected combined error rate is 7.66%. If we would perform 2000 studies designed with these error rates, we would observe 0.5 (the prior probability that H0 is true) × 0.033 (the alpha level) × 2000 = 33 Type 1 errors, and 0.5 (the prior probability that H1 is true) × 0.252 (the Type 2 error rate) × 2000 = 252 Type 2 errors. Since we weigh Type 1 errors 4 times as much as Type 2 errors, we multiple the cost of the 33 Type 1 errors by 4, which makes 4×33 = 132, and to keep the weighted error rate between 0 and 1, we also multiple the 1000 studies where we expect H0 to be true by 4, such that the weighted combined error rate is (132+252)/(4000 + 1000) = 0.0768.</p>
<p>If we choose to compute balanced error rates, we not surprisingly get, with n = 64 per conditions, which gives us 80% power with an alpha of 5%, exactly these error rates, as this scenario actually put the cost of a Type 1 error are 4 times the cost of a Type 2 error.</p>
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res4</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/optimal_alpha.html">optimal_alpha</a></span><span class="op">(</span>power_function <span class="op">=</span> <span class="st">"pwr.t.test(d=0.5, n=64, sig.level = x, type='two.sample', alternative='two.sided')$power"</span>,
              error <span class="op">=</span> <span class="st">"balance"</span>,
              costT1T2 <span class="op">=</span> <span class="fl">4</span>,
              priorH1H0 <span class="op">=</span> <span class="fl">1</span>,
              verbose <span class="op">=</span> <span class="cn">FALSE</span>, 
              printplot <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<p><img src="intro_to_justifieR_files/figure-html/cost%20balance-1.png" width="576"></p>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res4</span><span class="op">$</span><span class="va">alpha</span></code></pre></div>
<pre><code>## [1] 0.04974484</code></pre>
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res4</span><span class="op">$</span><span class="va">beta</span></code></pre></div>
<pre><code>## [1] 0.1991642</code></pre>
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res4</span><span class="op">$</span><span class="va">errorrate</span></code></pre></div>
<pre><code>## [1] 0.07962871</code></pre>
<p>If we would perform 2000 studies designed with these error rates, we would observe 0.5 (the prior probability that H0 is true) × 0.05 (the alpha level) × 2000 = 50 Type 1 errors, and 0.5 (the prior probability that H1 is true) × 0.200 (the Type 2 error rate) × 2000 = 200 Type 2 errors, for a total of 250 errors. However, we weigh Type 1 errors 4 times as much as Type 2 errors (or 4:1). So the cost is or the 50 Type 1 errors is 4 × 50 = 200 (hence the balanced error rates, as the costs of Type 1 errors is now balanced with the cost for Type 2 errors). Because Type 1 errors are weighed four times as much as Type 2 errors, 0.8 of the weight is determined by Type 1 errors, and 0.2 of the weight is determined by Type 2 errors, and the weighted combined error rate is (0.8 × 0.05 + 0.2 × 0.20) = 0.08.</p>
</div>
<div id="prior-probabilities-of-h0-and-h1" class="section level1">
<h1 class="hasAnchor">
<a href="#prior-probabilities-of-h0-and-h1" class="anchor"></a>Prior probabilities of H0 and H1</h1>
<p>So far, we have assumed that H0 and H1 are equally likely. We can change the prior probabilities that H0 is true (and you will observe a Type 1 error), or that the alternative hypothesis (H1) is true (and you will observe a Type 2 error). By incorporating these expectations, you can minimize or balance error rates in the long run (assuming your priors are correct). Priors can be specified using the <code>priorH1H0</code> argument, which by default is 1 (H1 and H0 are equally likely). Setting it to 4 means you think the alternative hypothesis (and hence, Type 2 errors) are 4 times more likely than that the null hypothesis is true (and hence, Type 1 errors).</p>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res5</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/optimal_alpha.html">optimal_alpha</a></span><span class="op">(</span>power_function <span class="op">=</span> <span class="st">"pwr.t.test(d=0.5, n=64, sig.level = x, type='two.sample', alternative='two.sided')$power"</span>,
              error <span class="op">=</span> <span class="st">"minimize"</span>,
              costT1T2 <span class="op">=</span> <span class="fl">1</span>,
              priorH1H0 <span class="op">=</span> <span class="fl">4</span>,
              verbose <span class="op">=</span> <span class="cn">FALSE</span>, 
              printplot <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<p><img src="intro_to_justifieR_files/figure-html/prior-1.png" width="576"></p>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res5</span><span class="op">$</span><span class="va">alpha</span></code></pre></div>
<pre><code>## [1] 0.2461469</code></pre>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res5</span><span class="op">$</span><span class="va">beta</span></code></pre></div>
<pre><code>## [1] 0.04831345</code></pre>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res5</span><span class="op">$</span><span class="va">errorrate</span></code></pre></div>
<pre><code>## [1] 0.08788013</code></pre>
<p>If you think H1 is four times more likely to be true than H0, you need to worry less about Type 1 errors, and now the alpha that minimizes the weighted error rates is 24.6%, with a power of 4.8%. If we would perform 2000 studies designed with these error rates, and we expect H1 is true 4 times as often as H0, then we expect H0 to be true in 20% (or 400) of the studies, and H1 to be true in 80% (or 1600) of the studies (as 1:4 = 20:80 = 400:1600). So, we should expect to observe 0.2 (the prior probability that H0 is true) × 0.246 (the alpha level) × 2000 = 98.4 Type 1 errors, and 0.8 (the prior probability that H1 is true) × 0.0483 (the Type 2 error rate) × 2000 = 77.3 Type 2 errors, for a total of 175.7 errors. Because we expect H1 to be four times as likely as H0, we weigh Type 2 errors for 0.8, and Type 1 errors for 0.2. The weighted combined error rate is (0.2 × 0.246 + 0.8 × 0.0483) = 0.08784.</p>
<p>The decision about priors is always subjective, as is the case in any decision under uncertainty. The more certain you are about auxiliary hypotheses and the stronger the theory, the higher your prior might be that you are right. Also, when you conduct a replication study, the prior probability of the hypothesis should usually be higher than when attempting to find a novel effect. The more a prediction goes against things we know or expect to be true, the more likely H0 should be. But when designing any study, we need to consider prior probabilities. You always make a choice - even if you choose to assume H0 is equally likely as H1.</p>
</div>
<div id="sample-size-justification" class="section level1">
<h1 class="hasAnchor">
<a href="#sample-size-justification" class="anchor"></a>Sample Size Justification</h1>
<p>So far we have only discussed how to justify the alpha level given a fixed sample size. However, in practice researchers usually want to conduct power analysis. This can be incorporated smoothly when minimizing or balancing error rates. To do so, you simply need to specify the weighted combined error rate you are aiming for and the function <code>optimal_sample</code> will return the sample size as well as the alpha and beta required to achieve the desired weighted combined error rate.</p>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res6</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/optimal_sample.html">optimal_sample</a></span><span class="op">(</span>power_function <span class="op">=</span> <span class="st">"pwr.t.test(d=0.5, n = sample_n, sig.level = x, type='two.sample', alternative='two.sided')$power"</span>, 
                       error <span class="op">=</span> <span class="st">"minimize"</span>, 
                       errorgoal <span class="op">=</span> <span class="fl">0.05</span>, 
                       costT1T2 <span class="op">=</span> <span class="fl">1</span>,
                       priorH1H0 <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>

<span class="va">res6</span></code></pre></div>
<pre><code>## $alpha
## [1] 0.046575
## 
## $beta
## [1] 0.05311184
## 
## $errorrate
## [1] 0.04984342
## 
## $objective
## [1] 0.04984342
## 
## $samplesize
## [1] 105</code></pre>
<p>Using the code above, we see that if we aim to achieve a combined error rate of 0.05, we need 105 participants in each of two conditions for an independent <em>t</em>-test.</p>
</div>
<div id="specifying-power-functions" class="section level1">
<h1 class="hasAnchor">
<a href="#specifying-power-functions" class="anchor"></a>Specifying power functions</h1>
<p>So far we have used only one function from the <code>pwr</code> package to specify the power function. However, any function can be entered. Below we illustrate some additional approaches. It is important to specify a power function that returns the power, where the alpha level is a variable x, and where the output is a power value between 0 and 1 (e.g., 0.8).</p>
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">design_result</span> <span class="op">&lt;-</span> <span class="fu">Superpower</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/Superpower/man/ANOVA_design.html">ANOVA_design</a></span><span class="op">(</span>
  design <span class="op">=</span> <span class="st">"2b"</span>,
  n <span class="op">=</span> <span class="fl">64</span>,
  mu <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">0.5</span><span class="op">)</span>,
  sd <span class="op">=</span> <span class="fl">1</span>
<span class="op">)</span></code></pre></div>
<pre><code>## Registered S3 methods overwritten by 'lme4':
##   method                          from
##   cooks.distance.influence.merMod car 
##   influence.merMod                car 
##   dfbeta.influence.merMod         car 
##   dfbetas.influence.merMod        car</code></pre>
<p><img src="intro_to_justifieR_files/figure-html/power_alt-1.png" width="672"></p>
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">Superpower</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/Superpower/man/ANOVA_exact.html">ANOVA_exact</a></span><span class="op">(</span><span class="va">design_result</span>, alpha_level <span class="op">=</span> <span class="fl">0.05</span>, verbose <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span><span class="op">$</span><span class="va">main_results</span><span class="op">$</span><span class="va">power</span><span class="op">/</span><span class="fl">100</span></code></pre></div>
<pre><code>## [1] 0.8014596</code></pre>
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">Superpower</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/Superpower/man/power_oneway_between.html">power_oneway_between</a></span><span class="op">(</span><span class="va">design_result</span>, alpha_level <span class="op">=</span> <span class="fl">0.05</span><span class="op">)</span><span class="op">$</span><span class="va">power</span><span class="op">/</span><span class="fl">100</span></code></pre></div>
<pre><code>## [1] 0.8014596</code></pre>
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">pwr.t.test</span><span class="op">(</span>d<span class="op">=</span><span class="fl">0.5</span>, n<span class="op">=</span><span class="fl">64</span>, sig.level <span class="op">=</span> <span class="fl">0.05</span>, type<span class="op">=</span><span class="st">'two.sample'</span>, alternative<span class="op">=</span><span class="st">'two.sided'</span><span class="op">)</span><span class="op">$</span><span class="va">power</span></code></pre></div>
<pre><code>## [1] 0.8014596</code></pre>
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res7</span> <span class="op">&lt;-</span> <span class="fu">JustifyAlpha</span><span class="fu">::</span><span class="fu"><a href="../reference/optimal_alpha.html">optimal_alpha</a></span><span class="op">(</span>power_function <span class="op">=</span> <span class="st">"Superpower::power_oneway_between(design_result, alpha_level = x)$power/100"</span>,
              error <span class="op">=</span> <span class="st">"minimize"</span>,
              costT1T2 <span class="op">=</span> <span class="fl">1</span>,
              priorH1H0 <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>

<span class="va">res7</span><span class="op">$</span><span class="va">alpha</span></code></pre></div>
<pre><code>## [1] 0.09978841</code></pre>
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res7</span><span class="op">$</span><span class="va">beta</span></code></pre></div>
<pre><code>## [1] 0.1215426</code></pre>
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res7</span><span class="op">$</span><span class="va">errorrate</span></code></pre></div>
<pre><code>## [1] 0.1106655</code></pre>
<div class="sourceCode" id="cb54"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res7</span><span class="op">$</span><span class="va">plot</span></code></pre></div>
<p><img src="intro_to_justifieR_files/figure-html/power_alt-2.png" width="672"></p>
<div class="sourceCode" id="cb55"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res8x</span> <span class="op">&lt;-</span> <span class="fu">JustifyAlpha</span><span class="fu">::</span><span class="fu"><a href="../reference/optimal_alpha.html">optimal_alpha</a></span><span class="op">(</span>power_function <span class="op">=</span> <span class="st">"Superpower::ANOVA_exact( (Superpower::ANOVA_design(design = '2b', n = 64, mu = c(0, 0.5), sd = 1, plot = FALSE)), alpha_level = x, verbose = FALSE)$main_results$power/100"</span>,
              error <span class="op">=</span> <span class="st">"minimize"</span>,
              costT1T2 <span class="op">=</span> <span class="fl">1</span>,
              priorH1H0 <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>

<span class="va">res8x</span><span class="op">$</span><span class="va">alpha</span></code></pre></div>
<pre><code>## [1] 0.09978841</code></pre>
<div class="sourceCode" id="cb57"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res8x</span><span class="op">$</span><span class="va">beta</span></code></pre></div>
<pre><code>## [1] 0.1215426</code></pre>
<div class="sourceCode" id="cb59"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res8x</span><span class="op">$</span><span class="va">errorrate</span></code></pre></div>
<pre><code>## [1] 0.1106655</code></pre>
<div class="sourceCode" id="cb61"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res8x</span><span class="op">$</span><span class="va">plot</span></code></pre></div>
<p><img src="intro_to_justifieR_files/figure-html/power_alt-3.png" width="672"></p>
</div>
<div id="avoiding-the-lindley-paradox" class="section level1">
<h1 class="hasAnchor">
<a href="#avoiding-the-lindley-paradox" class="anchor"></a>Avoiding the Lindley Paradox</h1>
<p>Sometimes we don’t know the prior odds or the effect size of interest. In this case we can justify the alpha level by aiming to avoid the Lindley paradox. The Lindley paradox arises from the difference between error rate control and likelihood ratios in statistics. When the power is high, it is possible that a significant <em>p</em>-value is actually more likely to occur under the alternative than under the null hypothesis. This situation, where we reject the null hypothesis because p &lt; alpha, but the <em>evidence</em> based on the likelihood suggests the observed data is more likely under the null hypothesis than the alternative hypothesis, is considered the Lindley paradox. The figure below shows that the steeper the <em>p</em>-value distribution (which occurs as the sample size increases) the more to the left the point where the expected <em>p</em>-value distribution under the alternative will cross the uniform <em>p</em>-value distribution under H0. The solution to prevent Lindley’s paradox is to lower the alpha level as a function of the sample size.</p>
<div class="figure">
<img src="intro_to_justifieR_files/figure-html/p-plot-1.png" alt="*P*-value distributions for a two-sided independent *t*-test with N = 150 and d = 0.5 (black curve) or d = 0 (horizontal dashed line) which illustrates how *p*-values just below 0.05 can be more likely when there is no effect than when there is an effect." width="672"><p class="caption">
<em>P</em>-value distributions for a two-sided independent <em>t</em>-test with N = 150 and d = 0.5 (black curve) or d = 0 (horizontal dashed line) which illustrates how <em>p</em>-values just below 0.05 can be more likely when there is no effect than when there is an effect.
</p>
</div>
<p>A Bayes factor and a <em>p</em>-value are directly related, given a prior, and a sample size. They can both be computed directly from the <em>t</em>-value. In the plot below we see the Bayes factor (plotted on the vertical axis) and the <em>p</em>-value (plotted on the horizontal axis) for an independent <em>t</em>-test with 100 participants in each condition.</p>
<div class="sourceCode" id="cb62"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">n1</span> <span class="op">&lt;-</span> <span class="fl">100</span>
<span class="va">n2</span> <span class="op">&lt;-</span> <span class="fl">100</span>

<span class="va">loops</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span>from <span class="op">=</span> <span class="fl">0</span>, to <span class="op">=</span> <span class="fl">3</span>, by <span class="op">=</span> <span class="fl">0.001</span><span class="op">)</span>
<span class="va">p</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">loops</span><span class="op">)</span><span class="op">)</span>
<span class="va">bf</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">loops</span><span class="op">)</span><span class="op">)</span>
<span class="va">d</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">loops</span><span class="op">)</span><span class="op">)</span>
<span class="va">tval</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">loops</span><span class="op">)</span><span class="op">)</span>
<span class="va">i</span> <span class="op">&lt;-</span> <span class="fl">0</span>

<span class="kw">for</span><span class="op">(</span><span class="va">t</span> <span class="kw">in</span> <span class="va">loops</span><span class="op">)</span><span class="op">{</span>
  <span class="va">i</span> <span class="op">&lt;-</span> <span class="va">i</span><span class="op">+</span><span class="fl">1</span>
  <span class="va">bf</span><span class="op">[</span><span class="va">i</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="fu">BayesFactor</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/BayesFactor/man/ttest.tstat.html">ttest.tstat</a></span><span class="op">(</span><span class="va">t</span>, <span class="va">n1</span>, <span class="va">n2</span><span class="op">)</span><span class="op">$</span><span class="va">bf</span><span class="op">)</span>
  <span class="va">p</span><span class="op">[</span><span class="va">i</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fl">2</span><span class="op">*</span><span class="fu"><a href="https://rdrr.io/r/stats/TDist.html">pt</a></span><span class="op">(</span><span class="va">t</span>, <span class="op">(</span><span class="op">(</span><span class="va">n1</span> <span class="op">+</span> <span class="va">n2</span><span class="op">)</span> <span class="op">-</span> <span class="fl">2</span><span class="op">)</span>, lower<span class="op">=</span><span class="cn">FALSE</span><span class="op">)</span>
  <span class="va">tval</span><span class="op">[</span><span class="va">i</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="va">t</span>
  <span class="va">d</span><span class="op">[</span><span class="va">i</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="va">t</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="op">(</span><span class="fl">1</span><span class="op">/</span><span class="va">n1</span><span class="op">)</span><span class="op">+</span><span class="op">(</span><span class="fl">1</span><span class="op">/</span><span class="va">n2</span><span class="op">)</span><span class="op">)</span>
<span class="op">}</span>

<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">p</span>, <span class="va">bf</span>, type<span class="op">=</span><span class="st">"l"</span>, lty<span class="op">=</span><span class="fl">1</span>, lwd<span class="op">=</span><span class="fl">2</span>, log <span class="op">=</span> <span class="st">"y"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span><span class="op">(</span>v <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">1</span>,<span class="fl">0.1</span><span class="op">)</span>, h <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span><span class="op">/</span><span class="fl">10</span>, <span class="fl">1</span><span class="op">/</span><span class="fl">3</span>, <span class="fl">1</span>, <span class="fl">3</span>, <span class="fl">10</span><span class="op">)</span>, col <span class="op">=</span> <span class="st">"gray"</span>, lty <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></code></pre></div>
<p><img src="intro_to_justifieR_files/figure-html/p-bf-1.png" width="672"></p>
<p>We can easily see which Bayes factor threshold corresponds to a specific <em>p</em>-value. For a Bayes factor of 1, we get a <em>p</em>-value of:</p>
<div class="sourceCode" id="cb63"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">p</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/which.min.html">which.min</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">bf</span><span class="op">-</span><span class="fl">1</span><span class="op">)</span><span class="op">)</span><span class="op">]</span></code></pre></div>
<pre><code>## [1] 0.0462172</code></pre>
<p>So, as long as the observed <em>p</em>-value is smaller than 0.046 the data will provide stronger support for H1 than for H0.</p>
<p><code>JustifyAlpha</code> allows users to directly compute the alpha level that enables them to avoid the Lindley paradox through the functions <code>ftestEvidence</code> and <code>ttestEvidence</code>, which calculate the alpha level that is needed so that a significance <em>p</em>-value is always more likely under the alternative hypothesis than under the null hypothesis, based on a specification of a prior for the alternative model. For a two sample <em>t</em>-test with 100 participants per group, we can do this using the following function.</p>
<div class="sourceCode" id="cb65"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">res8</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/ttestEvidence.html">ttestEvidence</a></span><span class="op">(</span><span class="st">"lindley"</span>, <span class="fl">100</span>, <span class="fl">100</span><span class="op">)</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span>
<span class="va">res8</span></code></pre></div>
<pre><code>## [1] 0.04625576</code></pre>
<p>This shows that an alpha level of at least 0.046 would be required to avoid the Lindley paradox. Of course, researchers can also use an informed prior, or use the the likelihood of the data under the effect size of the alternative hypothesis. There are many approaches to prevent Lindley’s paradox. All boil down to lowering the alpha level as a function of the sample size, but they differ slightly the relation between the sample size and the alpha level.</p>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Maximilian Maier, Daniel Lakens.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
